from __future__ import annotations

from typing import Protocol

from backend.app.domain.workflow_run import WorkflowRun


class WorkflowRunRepositoryProtocol(Protocol):
    def create(self, run: WorkflowRun) -> None: ...
    def get(self, run_id: str) -> WorkflowRun | None: ...
    def update(self, run: WorkflowRun) -> None: ...
    def list(self) -> list[WorkflowRun]: ...
